### ISSUE TITLE
Incorrect results with percent sign

### ISSUE THREAD

**Issue by kpcyrd** [jimmycuadra/rust-shellwords#1]
I troubleshooted this for a while in my program and noticed that shellwords returns a weird result if a percent is involved.

I wrote this test for shellwords:
```
#[test]
fn quoted_percent() {
    assert_eq!(split("abc '%foo bar%'").unwrap(), ["abc", "%foo bar%"]);
}
```

This is the current result on master:
```
failures:

---- tests::quoted_percent stdout ----
thread 'tests::quoted_percent' panicked at 'assertion failed: `(left == right)`
  left: `["abc", "%"]`,
 right: `["abc", "%foo bar%"]`', src/lib.rs:192:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I've had a quick look at the code but couldn't find the bug, I suspect there's something wrong with the `MAIN_PATTERN` regex. Note that this works if the percent sign is not quoted.

**Comment by jimmycuadra** [comment]
Thanks for the report. Fixed and included in the new [1.0.0 release](https://github.com/jimmycuadra/rust-shellwords/releases/tag/1.0.0).
